# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ntagent
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod tidy
    #- del /Q log\*
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0

    # flags:
    #   - -tags=etcd
      
    goos:
      - windows
      - linux

    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    #wrap_in_directory: true
    files:
      #- LICENSE.txt
      #- README.md
      #- CHANGELOG.md
      #- docs/*
      #- log/*
      - conf.yaml

#checksum:
# name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag  }}_{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
